apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bookinfo
  namespace: bookinfo
spec:
  host: '*.bookinfo.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
